### ISSUE TITLE
404

### ISSUE THREAD

**Issue by abitrolly** [openSUSE/obs-review-apps#10]
https://obs-reviewlab.opensuse.org/

I have no idea what is does. Decided to check and it is down.

**Comment by eduardoj** [comment]
That base URL should not point to something specific. It is not wrong that this root URL points to a 404 page.

This wiki page could give you a hint how Review apps should be used: https://github.com/openSUSE/open-build-service/wiki/Review-apps

**Comment by abitrolly** [comment]
I see. Are there any screenshots of this review app?

**Comment by eduardoj** [comment]
> I see. Are there any screenshots of this review app?

Better than that, you can see the review-app working, live, in every [pull request of the OBS project](https://github.com/openSUSE/open-build-service/pulls?q=is%3Apr+is%3Aopen+label%3Areview-app) that has the label `review-app`. Enter one of those pull requests, and click in the link provided with the preceeding comment: "Review app will appear here". Enjoy!

**Comment by abitrolly** [comment]
The review app website requires login to view, and the one from build.opensuse.org doesn't work.
